# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
    - name: Dotnet Test Reporter
      uses: bibipkins/dotnet-test-reporter@v1.4.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Test Results & Coverage'
        results-path: "**/*.trx"
        coverage-type: cobertura
        coverage-path: "**/coverage.cobertura.xml"
        coverage-threshold: 80